name: paisa_clone
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  chart_sparkline: ^1.0.13
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  google_fonts: ^5.1.0
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  ionicons: ^0.2.2
  line_icons: ^2.0.3
  material_design_icons_flutter: ^7.0.7296
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  flutter_native_splash: null
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  hive_generator: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon.png
  color_dark: "#121212"
  android: true
  ios: true
  android_12:
    image: assets/images/icon_light.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/icon_dark.png
    icon_background_color_dark: "#121212"

flutter:

  uses-material-design: true
  assets:
    - assets/images/icon.png
